export const state = {
    httpRequest: false,
    dataList: [],
    detailsData: [],
    authUser: {},
    Config: [],
    allMenus: [],
    Permissions: [],
    isConfigLoaded: false,
    pageDependencies: {},
    formType: 1,
    updateId: '',
    formObject : {},
    formFilter : {
        per_page : 15,
        status : '',
    },
    modalTitle :'',
    currentPage :'',
    currentPagination : 1,
    uploadProgress : 0,
    useDynamicHead: [],
    previousDataData: {},
    currentDate: null,
    currentDateTime: null,
};
