export { default as dataTable } from '@/components/table/dataTable.vue'
export { default as generalLayout } from '@/components/table/generalLayout.vue'
export { default as tableHeader } from '@/components/table/tableHeader.vue'
export { default as tableTop } from '@/components/table/tableTop.vue'
export { default as pageTop } from '@/components/pageTop.vue'
export { default as fromModal } from '@/components/fromModal.vue'
export { default as detailsModal } from '@/components/detailsModal.vue'
export { default as fileUpload } from '@/components/fileUpload.vue'
