export { default as dataTable } from '@/components/table/dataTable.vue'
export { default as tableTop } from '@/components/table/tableTop.vue'
export { default as pageTop } from '@/components/pageTop.vue'
// export { default as fromModal } from '@/components/fromModal.vue'
export { default as fromModal } from '@/components/fromModal.vue'
